name: Follower

on: push
# schedule:
#    - cron: '0 * * * *' 

jobs:
  insta:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run follower script
      run: |
        python cat_follow.py
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: |
          screenshot_login.png
          screenshot_after_click_followers.png
          screenshot_error.png
